//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerGuarantee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCaseInfor
    {
        public int CustomerCaseID { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string PhoneCustomer { get; set; }
        public string Email { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public string CarName { get; set; }
        public string CarAddress { get; set; }
        public string CarPhoneNumber { get; set; }
        public string InforFromCustomer { get; set; }
        public string BillNumber { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string CodeGenerate { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserEdit { get; set; }
        public string ThoiGianXuLy { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string GhiChuXuLy { get; set; }
        public string NgayGui { get; set; }
        public Nullable<System.DateTime> UserNgayGui { get; set; }
        public string UserTenNhaXe { get; set; }
        public string UserAddress { get; set; }
        public string USerSoDTNhaXe { get; set; }
        public Nullable<int> UserGuiType { get; set; }
        public string USerGuiTra { get; set; }
        public string UserSDTGiaoHang { get; set; }
        public string NguoiLienHe { get; set; }
        public string ProductSeri { get; set; }
        public string ProductNgayMua { get; set; }
        public string ProductTinhTrangLoi { get; set; }
        public string ProductPhukien { get; set; }
        public Nullable<int> PhuongThucGui { get; set; }
        public string TenGiaoNhan { get; set; }
        public string SoDienThoaiGiaoNhan { get; set; }
        public Nullable<int> HinhThucGui { get; set; }
        public string GhiChuPhatSinh { get; set; }
        public Nullable<System.DateTime> Step1 { get; set; }
        public Nullable<System.DateTime> Step2 { get; set; }
        public Nullable<System.DateTime> Step3 { get; set; }
        public Nullable<System.DateTime> Step4 { get; set; }
        public Nullable<System.DateTime> Step5 { get; set; }
    }
}
