//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerGuarantee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCaseInfor
    {
        public int CustomerCaseID { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string PhoneCustomer { get; set; }
        public string Email { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public string CarName { get; set; }
        public string CarAddress { get; set; }
        public string CarPhoneNumber { get; set; }
        public string InforFromCustomer { get; set; }
        public string BillNumber { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string CodeGenerate { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserEdit { get; set; }
        public string ThoiGianXuLy { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string GhiChuXuLy { get; set; }
        public string NgayGui { get; set; }
    }
}
