//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerGuarantee.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerCaseEntities : DbContext
    {
        public CustomerCaseEntities()
            : base("name=CustomerCaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerCaseInfor> CustomerCaseInfors { get; set; }
        public virtual DbSet<tUSer> tUSers { get; set; }
        public virtual DbSet<tCustomerUser> tCustomerUsers { get; set; }
    }
}
